apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-portal
  namespace: employee-portal
  labels:
    app: employee-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-portal
  template:
    metadata:
      labels:
        app: employee-portal
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: employee-portal
          image: REPLACE_WITH_ECR_URI:REPLACE_WITH_BUILD_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
